### ISSUE TITLE
Reevalutate the use of `file` in function names when Google calls them blobs

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#17]
In google storage bucket, a `file` is reffered to as a blob... should we also use the same naming?

I used file since its an easy to follow concept. However it might be nicer to keep names of concepts the same as in google cloud storage bucket documentation. This will lead to less confusion and easier lookup there. 

Why we shouldn't do the change could be that blob is not a very familiar concept whereas file is easy to understand for everyone. Even for people who might not be that interested in what storage bucket does behind the scenes.

There is also the option of calling them objects, but i think that would be even more confusing than `Blob`

blobs:
https://googleapis.dev/python/storage/latest/blobs.html

**Comment by thomasborgen** [comment]
@ChameleonTartu Please let me know what you think

**Comment by ChameleonTartu** [comment]
@thomasborgen I found an article: [Storage: Key terms](https://cloud.google.com/storage/docs/key-terms) and it seems that they call them `Objects` and the term `Blob` has leaked as an implementation-specific detail. I propose to use the term `File`, as a more precise definition of what is stored and it is well-known concept from OS systems.

**Comment by thomasborgen** [comment]
File it is then.
