### ISSUE TITLE
Add Material For MkDocs documentation

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#36]
This looks sexy and quite easy:

https://squidfunk.github.io/mkdocs-material/

No automagic like with sphinx, but since our package is so small then this should be enough.

For reference Reference
https://github.com/proofit404/stories

**Comment by ChameleonTartu** [comment]
@thomasborgen It makes sense. Also, I somehow don't like Sphinx. Let's try it out!
