### ISSUE TITLE
Add copyright notice in the License

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#42]
I'm not sure what should be written there. our names with emails?

if so something like: 

Copyright (c) 2020 Thomas Borgen<thomasborgen91@gmail.com>, Dmytro Chasovskyi<email?>

@ChameleonTartu would this make sense? and what email would you like?

**Comment by ChameleonTartu** [comment]
Do we use an MIT license? You can use my dmitriy.chasovskoy@gmail.com e-mail.
