### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#43]
With 3.9 the typing should be much nicer

The other repos i follow like `returns`, `dependencies`, `classes` are all dropping py 3.6 support because i believe that 3.6 and 3.9 does not work well for same codebase. 

I suggest we drop 3.6 and do a major release.

@ChameleonTartu thoughts?

**Comment by ChameleonTartu** [comment]
@thomasborgen I think it is an excellent idea. Let's do it :-)

**Comment by thomasborgen** [comment]
Without `returns` we now support `3.9` without loosing `3.6` :)
