### ISSUE TITLE
Consider removing Returns

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#45]
Returns library is still in early development with lots of breaking changes. Being hardlocked into a version just from using this library might be quite annoying.

We don't really "need" it either. People can hook Returns onto our functions if they want. 

What do you think @ChameleonTartu ?

**Comment by ChameleonTartu** [comment]
@thomasborgen I agree 100% with you. I have recently struggled to upgrade `returns` from v14 to v16, so I believe it would be a good idea to write a functional style without returns.

**Comment by thomasborgen** [comment]
@ChameleonTartu  i think v0.17 just got out aswell? :P have fun with that ^^
