### ISSUE TITLE
Add List Buckets Functionality

### ISSUE THREAD

**Issue by thomasborgen** [thomasborgen/storage-bucket#9]
Callable object name: ListBuckets
function name: list_buckets

init args: google.storage.Client
call args:
        prefix: Optional[str] = None,
        fields: Optional[Set] = None,
        projection: str = 'noAcl',
        project: Optional[str] = None

return ResultE[Set[Bucket]]

**Comment by ChameleonTartu** [comment]
@thomasborgen I have assigned you here by mistake. I will do this feature.
